server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  charset utf-8;

  location = / {
    return 302 /blog/;
  }

  location = /blog {
    return 301 /blog/;
  }

  location /blog/ {
    rewrite ^/blog/(.*)$ /$1 break;
    try_files $uri $uri.html $uri/ /index.html;
  }
}
